set(PYBIND11_FINDPYTHON ON)

find_package(pybind11 REQUIRED CONFIG)

file(GLOB_RECURSE PYTHON_WRAPPER_SOURCES CONFIGURE_DEPENDS src/*.cpp)

pybind11_add_module(SkeletonizationPython ${PYTHON_WRAPPER_SOURCES})