name: CI - SkeletonizationVisualizer

on:
    push:
        branches: [master]
        paths:
            - "SkeletonizationVisualizer/**"
            - '.github/workflows/CI-SkeletonizationVisualizer.yml'
    pull_request:
        branches: [master]
        paths:
            - "SkeletonizationVisualizer/**"
            - '.github/workflows/CI-SkeletonizationVisualizer.yml'

jobs:
    build-frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "npm"
                  cache-dependency-path: "SkeletonizationVisualizer/package-lock.json"

            - name: Install dependencies
              working-directory: SkeletonizationVisualizer
              run: npm ci

            - name: Run Prettier and ESLint
              working-directory: SkeletonizationVisualizer
              run: |
                  npm run prettier
                  npm run lint

            - name: Build React (Vite)
              working-directory: SkeletonizationVisualizer
              run: npm run build
